### ISSUE TITLE
Icons broken

### ISSUE THREAD

**Issue by rnarian** [Yummygum/city-lights-icons-atom#2]
Enabling the package unfortunately breaks the icons for me:

![bildschirmfoto 2017-11-06 um 10 17 43](https://user-images.githubusercontent.com/1174951/32433698-2bf9e670-c2dc-11e7-8b44-06bbe4c14dae.png)

**Comment by noudadrichem** [comment]
Hi @rnarian,

Did you try to completely uninstall the file-icons package and any other package? This do is very strange.

What OS and what version of atom are you running?

Let me know!

**Comment by robink** [comment]
Same issue here. (High Sierra, fresh install)

**Comment by noudadrichem** [comment]
Hi @robink, 

Do you have any other icon packages installed? This can give conflicts in class overwrites.

Let me know!

Sincerely

**Comment by rnarian** [comment]
Sorry for the late response. I disabled the other icon package that was used before (file-icons). I also tried to reinstall the plugins without any luck.

I don't think it is just class interference with another plugin as the icons do get rendered, but not 'the right way' somehow:

![rectangle](https://user-images.githubusercontent.com/1174951/34731230-083ac05c-f562-11e7-8734-3eb224916e30.png)

**Comment by noudadrichem** [comment]
Hi @rnarian,

Wow, this is very weird! The icons are SVGs. I think this may be a rendering problem.. Sad you can't fix it. What OS are you using and what version of Atom are you on?

Sincerely

**Comment by noudadrichem** [comment]
Hé @robink,

Are you sure you don't have any other icon packages installed?

Please let me know.

Sincerely
