### ISSUE TITLE
Icon colors without hover

### ISSUE THREAD

**Issue by carloscuesta** [Yummygum/city-lights-icons-atom#3]
Hello @Yummygum!

I really like the set of icons you've made ✨. But I would really like to use this icons without the hover feature. I mean seeing all the colors without having to be on that file specifically.

Could this be considered as a setting?

Thanks! 🎉

**Comment by noudadrichem** [comment]
Hi @carloscuesta,

We're very flattered you like the icons, this is an idea we'll take in consideration.

Sincerely

**Comment by noudadrichem** [comment]
I'm working on it. 😊

**Comment by carloscuesta** [comment]
Why this issue got closed? @noudadrichem
